export const authType = {
    AUTH_START:'AUTH_START', 
    AUTH_SUCCESS:'AUTH_SUCCESS', 
    AUTH_FAIL:'AUTH_FAIL', 
    AUTH_LOGOUT:'AUTH_LOGOUT',
    USER_PROFILE:'USER_PROFILE'
}

export const notifs = {
    NOTIF_RESET:'NOTIF_RESET', 
    NOTIF_SUCCESS:'NOTIF_SUCCESS', 
    NOTIF_FAIL:'NOTIF_FAIL'
}