export const authType = {
    AUTH_START:'AUTH_START', 
    AUTH_SUCCESS:'AUTH_SUCCESS', 
    AUTH_FAIL:'AUTH_FAIL', 
    AUTH_LOGOUT:'AUTH_LOGOUT',
    USER_PROFILE:'USER_PROFILE'
}

export const notifs = {
    NOTIF_RESET:'NOTIF_RESET', 
    NOTIF_SUCCESS:'NOTIF_SUCCESS', 
    NOTIF_FAIL:'NOTIF_FAIL'
}

export const lieuConsult = {
    GET_LIEUCONSULT:'GET_LIEUCONSULT',
    CREATE_LIEUCONSULT:'CREATE_LIEUCONSULT',
    DELETE_LIEUCONSULT:'DELETE_LIEUCONSULT',
    UPDATE_LIEUCONSULT:'UPDATE_LIEUCONSULT'
}

export const horaire = {
    GET_HORAIRE:'GET_HORAIRE',
    CREATE_HORAIRE:'CREATE_HORAIRE',
    DELETE_HORAIRE:'DELETE_HORAIRE',
    UPDATE_HORAIRE:'UPDATE_HORAIRE'
}

export const contact = {
    GET_CONTACT:'GET_CONTACT',
    CREATE_CONTACT:'CREATE_CONTACT',
    DELETE_CONTACT:'DELETE_CONTACT',
    UPDATE_CONTACT:'UPDATE_CONTACT'
}

