export const authType = {
    AUTH_START:'AUTH_START', 
    AUTH_SUCCESS:'AUTH_SUCCESS', 
    AUTH_FAIL:'AUTH_FAIL', 
    AUTH_LOGOUT:'AUTH_LOGOUT',
    USER_PROFILE:'USER_PROFILE'
}

export const notifs = {
    NOTIF_RESET:'NOTIF_RESET', 
    NOTIF_SUCCESS:'NOTIF_SUCCESS', 
    NOTIF_FAIL:'NOTIF_FAIL'
}

export const lieuConsult = {
    GET_LIEUCONSULT:'GET_LIEUCONSULT',
    CREATE_LIEUCONSULT_START:'CREATE_LIEUCONSULT_START',
    CREATE_LIEUCONSULT_SUCCESS:'CREATE_LIEUCONSULT_SUCCESS',
    CREATE_LIEUCONSULT_FAIL:'CREATE_LIEUCONSULT_FAIL',
    DELETE_LIEUCONSULT_START:'DELETE_LIEUCONSULT_START',
    DELETE_LIEUCONSULT_FAIL:'DELETE_LIEUCONSULT_FAIL',
    DELETE_LIEUCONSULT_SUCCESS:'DELETE_LIEUCONSULT_SUCCESS',
    UPDATE_LIEUCONSULT_START:'UPDATE_LIEUCONSULT_START',
    UPDATE_LIEUCONSULT_FAIL:'UPDATE_LIEUCONSULT_FAIL',
    UPDATE_LIEUCONSULT_SUCCESS:'UPDATE_LIEUCONSULT_SUCCESS',
}


